using System.Collections;
using UnityEngine;
using UnityEngine.U2D;

public class CameraController : MonoBehaviour
{
    public float smoothSpeed = 0.125f;
    public Vector3 offset = new Vector3(0, 0, -10);
    public float smoothTime = 0.075f;
    public float zoomLevel = 2f;
    private Vector3 velocity = Vector3.zero;
    private Transform target;

    public float minSmoothTime = 0.1f; // УжМв РЬЕП МгЕЕ
    public float maxSmoothTime = 0.5f; // УжДы РЬЕП МгЕЕ
    public float distanceThreshold = 5f; // МгЕЕ СЖР§РЛ НУРлЧв АХИЎ

    public int assetsPPU = 200; // ЧШМП Цл РЏДж
    public int refResolutionX = 1920; // ТќСЖ ЧиЛѓЕЕ X
    public int refResolutionY = 1080; // ТќСЖ ЧиЛѓЕЕ Y

    public void SetTarget(Transform newTarget)
    {
        target = newTarget;
    }
    public void SetPixelPerfect(int resolutionX = 0, int resolutionY = 0)
    {
        PixelPerfectCamera pixelPerfectCamera = Camera.main.GetComponent<PixelPerfectCamera>();
        if (pixelPerfectCamera == null)
        {
            pixelPerfectCamera = Camera.main.gameObject.AddComponent<PixelPerfectCamera>();
        }
        pixelPerfectCamera.assetsPPU = assetsPPU;
        if(resolutionX != 0 && resolutionY != 0)
        {
            pixelPerfectCamera.refResolutionX = resolutionX;
            pixelPerfectCamera.refResolutionY = resolutionY;
        }
        else
        {
            pixelPerfectCamera.refResolutionX = refResolutionX;
            pixelPerfectCamera.refResolutionY = refResolutionY;
        }
        pixelPerfectCamera.upscaleRT = true;
        pixelPerfectCamera.pixelSnapping = true;
        pixelPerfectCamera.stretchFill = true;
        pixelPerfectCamera.refResolutionX = (int)(refResolutionX / zoomLevel);
        pixelPerfectCamera.refResolutionY = (int)(refResolutionY / zoomLevel);
    }
    public IEnumerator MoveToPosition(Transform targetTransform)
    {
        target = null;
        Vector3 targetPosition = new Vector3(targetTransform.position.x, targetTransform.position.y, -10);
        while (Vector3.Distance(transform.position, targetPosition) > 0.1f) // СЖАЧ МіСЄ
        {
            Vector3 smoothedPosition = Vector3.Lerp(transform.position, targetPosition, smoothTime);
            transform.position = smoothedPosition;
            yield return null;
        }
        transform.position = targetPosition;
    }

    private IEnumerator SmoothMove(Transform targetTransform)
    {
        target = null;
        Vector3 targetPosition = new Vector3(targetTransform.position.x, targetTransform.position.y, -10);
        // ФЋИоЖѓ РЬЕП
        while (Vector3.Distance(transform.position, targetPosition) > 0.1f)
        {
            // ДыЛѓАњРЧ АХИЎПЁ ЕћЖѓ smoothTimeРЛ ЕПРћРИЗЮ СЖР§
            float distance = Vector3.Distance(transform.position, targetPosition);
            float smoothTime = Mathf.Lerp(minSmoothTime, maxSmoothTime, Mathf.Clamp01(distance / distanceThreshold));

            Vector3 smoothedPosition = Vector3.Lerp(transform.position, targetPosition, smoothTime);
            transform.position = smoothedPosition;
            yield return null;
        }

        transform.position = targetTransform.position; // while ЙЎ СОЗс ШФ РЇФЁИІ СЄШЎШї РЯФЁНУХД
    }

    public IEnumerator ResetCameraAndTarget(float time)
    {
        yield return new WaitForSeconds(time);
        // ФЋИоЖѓИІ ПјЗЁ РЇФЁЗЮ ЕЧЕЙИЎБт
        MyPlayerController myPlayer = Managers.Object.MyPlayer;        
        MoveToPosition(myPlayer.transform);

        // ХИАйРЛ ЧУЗЙРЬОюЗЮ МГСЄЧЯБт
        if (myPlayer.gameObject.activeSelf == false)
        {
            myPlayer.gameObject.SetActive(true);
        }
        SetTarget(Managers.Object.MyPlayer.transform);
    }

    private void LateUpdate()
    {
        if (target != null)
        {
            Vector3 desiredPosition = new Vector3(target.position.x, target.position.y, -10);
            Vector3 smoothedPosition = Vector3.Lerp(transform.position, desiredPosition, smoothSpeed);
            transform.position = smoothedPosition;
        }
    }
}